version: '3.4'

services:
  cs333project:
    image: cs333project
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 NaiveBayesFilter.py "]
    ports:
      - 5678:5678
